### ISSUE TITLE
Errors uploading a file

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/maia-be#3]
Attempting to upload the file to the corpus I get the following error message:

```
{
    "timestamp": "2024-01-11T13:45:48.510+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "I/O error on POST request for \"https://localhost:7300/texto/resource/53/upload\": too many bytes written",
    "path": "/maia/texto/resource/53/upload"
}
```

Nevertheless, when I reopen the corpus explorer, the file appears correctly uploaded.

[loremipsum3.txt](https://github.com/klab-ilc-cnr/maia-be/files/13903962/loremipsum3.txt)

**Comment by davide-albanesi-ilc** [comment]
Bug has been fixed
